In [1]:
import numpy as np

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
world.reset()

NameError: name 'world' is not defined

In [4]:
import getpass
user = getpass.getuser()

In [5]:
from omni.isaac.kit import SimulationApp

usd_path = f"omniverse://localhost/Users/{user}/test_hand.usd"


simulation_app = SimulationApp({"headless": True, "open_usd": usd_path, "livesync_usd": usd_path})


Starting kit application with the fillowing args:  ['/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps', '--portable', '--no-window']
Passing the following args to the base kit application:  ['-f', '/home/yizhou/.local/share/jupyter/runtime/kernel-787d72c2-86e6-4447-8af6-c14fd0f1a78b.json

OmniAssetFileFormat


[1.748s] [ext: omni.mdl-0.1.0] startup
[1.772s] [ext: omni.kit.menu.create-1.0.2] startup
[1.774s] [ext: omni.kit.window.file_exporter-1.0.4] startup
[1.775s] [ext: omni.kit.window.drop_support-1.0.0] startup
[1.776s] [ext: omni.kit.material.library-1.3.10] startup
[1.780s] [ext: omni.kit.window.property-1.6.3] startup
[1.782s] [ext: omni.kit.context_menu-1.3.9] startup
[1.787s] [ext: omni.kit.window.file_importer-1.0.4] startup
[1.788s] [ext: omni.kit.stage_templates-1.1.2] startup
[1.790s] [ext: omni.kit.widget.stage-2.6.15] startup
[1.796s] [ext: omni.kit.window.file-1.3.16] startup
[1.799s] [ext: omni.debugdraw-0.1.0] startup
[1.806s] [ext: omni.kit.window.content_browser-2.4.28] startup
[1.819s] [ext: omni.kit.widget.prompt-1.0.1] startup
[1.820s] [ext: omni.kit.property.usd-3.14.8] startup
[1.861s] [ext: omni.hydra.engine.stats-1.0.0] startup
[1.868s] [ext: omni.kit.widget.settings-1.0.0] startup
[1.870s] [ext: omni.graph.tools-1.3.5] startup
[1.904s] [ext: omni.graph.core-2.27.0

2022-07-26 03:40:51 [2,124ms] [Error] [rtx.neuraylib.plugin] [DYNLIB:IO]   0.1   DYNLIB io   error: /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so: cannot open shared object file: No such file or directory
2022-07-26 03:40:51 [2,124ms] [Error] [rtx.neuraylib.plugin] [INDEX:MAIN]   0.1   INDEX  main error: Failed to load /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so


Warp initialized:
   Version: 0.2.1
   Using CUDA device: NVIDIA GeForce RTX 3090
   Using CPU compiler: /usr/bin/g++
[2.958s] [ext: omni.kit.window.preferences-1.2.1] startup
[2.998s] [ext: omni.kit.ui_test-1.2.0] startup
[3.001s] [ext: omni.graph.ui-1.6.1] startup
[3.032s] [ext: omni.kvdb-0.0.0] startup
[3.036s] [ext: omni.kit.widget.searchfield-1.0.6] startup
[3.039s] [ext: omni.convexdecomposition-1.4.12] startup
[3.043s] [ext: omni.graph.action-1.17.0] startup
[3.059s] [ext: omni.localcache-0.0.0] startup
[3.064s] [ext: omni.usdphysics-1.4.12] startup
[3.067s] [ext: omni.graph.scriptnode-0.5.0] startup
[3.070s] [ext: omni.physx-1.4.12-5.1] startup
[3.100s] [ext: omni.kit.usd_undo-0.1.0] startup
[3.102s] [ext: omni.graph.nodes-1.25.0] startup
[3.127s] [ext: omni.physx.commands-1.4.12-5.1] startup
[3.134s] [ext: omni.syntheticdata-0.2.1] startup
[3.188s] [ext: omni.physx.ui-1.4.12-5.1] startup
[3.287s] [ext: omni.warp-0.2.1] startup
[5.526s] [ext: omni.kit.renderer.capture-0.0.0] st

In [6]:
from omni.isaac.core import World
world = World()

In [7]:
from hand_env import HandEnv

# env = HandEnv("/World/Hand/Bones/l_carpal_mid", "/World/Hand*/Bones/l_thumbSkeleton_grp/l_distalThumb_mid")
env = HandEnv("/World/Hand*", "/World/Hand*/Bones/l_thumbSkeleton_grp/l_distalThumb_mid")

In [8]:
world.reset()

ndow.generic-1.3.8] startup
[6.530s] [ext: omni.isaac.utils-0.1.11] startup
[6.534s] [ext: omni.isaac.universal_robots-0.2.1] startup
[6.536s] [ext: omni.kit.property.audio-1.0.5] startup
[6.538s] [ext: omni.kit.property.skel-1.0.1] startup
[6.540s] [ext: omni.kit.property.render-1.1.0] startup
[6.541s] [ext: omni.kit.property.camera-1.0.3] startup
[6.543s] [ext: omni.kit.property.geometry-1.2.0] startup
[6.545s] [ext: omni.kit.property.light-1.0.5] startup
[6.548s] [ext: omni.kit.property.transform-1.0.2] startup
[6.552s] [ext: omni.isaac.occupancy_map-0.2.4] startup
[6.568s] [ext: omni.ui.scene-1.4.6] startup
[6.576s] [ext: omni.kit.window.console-0.2.0] startup
[6.584s] [ext: omni.kit.window.status_bar-0.1.1] startup
[6.589s] [ext: omni.kit.property.bundle-1.2.4] startup
[6.591s] [ext: omni.kit.menu.file-1.0.8] startup
[6.593s] [ext: omni.kit.manipulator.viewport-1.0.6] startup
[6.596s] [ext: omni.isaac.urdf-0.2.2] startup
[6.628s] [ext: omni.isaac.dofbot-0.2.0] startup
[6.630s] [ex

In [9]:
env.start()
world.scene.add(env.robots)

simlation context numpy None
num_envs 2
2022-07-26 03:41:06 [16,674ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'baseFixedJoint' in articulation metatype
2022-07-26 03:41:06 [16,674ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'baseFixedJoint' in articulation metatype
2022-07-26 03:41:06 [16,674ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'baseFixedJoint' in articulation metatype
2022-07-26 03:41:06 [16,674ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'SphericalJoint' in articulation metatype
2022-07-26 03:41:06 [16,674ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'SphericalJoint:0' in articulation metatype
2022-07-26 03:41:06 [16,674ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'SphericalJoint:1' in articulation metatype
2022-07-26 03:41:06 [16,674ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'SphericalJoint:2' in articulation metatype
2022-07-26 03:41:06 [16,674ms] [Warn

sors.plugin] Duplicate joint name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41:06 [16,676ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41:06 [16,676ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41:06 [16,677ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41:06 [16,677ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41:06 [16,677ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41:06 [16,677ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41:06 [16,677ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'RevoluteJoint' in articulation metatype
2022-07-26 03:41

In [10]:
env.robots.get_world_poses()

(array([[ 1.1175871e-08, -3.7252903e-09,  5.0000000e-01],
        [ 1.0000000e+00, -3.7252903e-09,  5.0000000e-01]], dtype=float32),
 array([[1.0000001e+00, 1.1175871e-08, 5.5879354e-09, 3.0733645e-08],
        [1.0000001e+00, 1.1175871e-08, 5.5879354e-09, 3.0733645e-08]],
       dtype=float32))

In [11]:
# pos = np.array([[ 0.5, -0., 0.5]], dtype=np.float32)
# env.robots.set_world_poses(positions=pos)

In [12]:
world.step(render=True)
# world.render()

In [13]:
world.reset()

2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'baseFixedJoint' in articulation metatype
2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'baseFixedJoint' in articulation metatype
2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'baseFixedJoint' in articulation metatype
2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplicate joint name 'SphericalJoint' in articulation metatype
2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'SphericalJoint:0' in articulation metatype
2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'SphericalJoint:1' in articulation metatype
2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplicate DOF name 'SphericalJoint:2' in articulation metatype
2022-07-26 03:41:08 [19,174ms] [Warning] [omni.physx.tensors.plugin] Duplica

In [14]:
env.robots.get_joint_positions()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
import time

In [ ]:
for i in range(10):
    pos = np.array([
        [0,  0.2*i,  0,
         0., 0., 0., 
         0., 0., 0., 
         0., 0., 0., 
         0., 0., 0., 
         0, -1, -1, -1, -1,
         0, -1.5, -1.5, -1.5, -1.5, 
        ],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0, 0, 0, 0, 0,
        ],
    ])

    # pos = np.random.randn(2,25)
    time.sleep(0.5)
    env.robots.set_joint_positions(pos) # 
    world.step(render=True)

In [ ]:
pos = np.zeros((1,25)) # np.random.randn(1, 25) # 

In [ ]:
env.robots._physics_view.dof_paths[0]

In [ ]:
world.reset()

In [ ]:
jacobians = env.robots._physics_view.get_jacobians()

In [ ]:
jacobians.shape

In [ ]:
env.robots._physics_view.jacobian_shape

In [ ]:
jacobians[0].shape

In [ ]:
joint_v = np.array([[
     0,  0,  0,
     0., 0., 0., 
     0., 0., 0., 
     0., 0., 0., 
     1., 0., 0., 
     0, 0, 0, 0, 0,
     0, 0, 0, 0, 0
]]).transpose()

In [ ]:
joint_v.shape

In [ ]:
delta_pos_rot = np.matmul(jacobians[0], joint_v)
for i in range(len(delta_pos_rot)):
    print(i, delta_pos_rot[i].transpose())

# Jacobian

In [ ]:
world.reset()
world.step(render=True)

In [ ]:
thumb_pos, thumb_rot = env.xforms.get_world_poses()

In [ ]:
thumb_rot = thumb_rot[:,[1,2,3,0]] # WXYZ -> XYZW

In [ ]:
thumb_pos, thumb_rot

In [ ]:
target_pos = np.array([[-0.37809137,  -0.3650283  , 0.05804292]])

In [ ]:
target_pos[...,0] += 0.1

In [ ]:
target_pos

In [ ]:
env.move_finger_to_fast(target_pos, thumb_rot, world)

In [ ]:
for _ in range(100):
    world.step(render=True)
    thumb_pos, thumb_rot = env.xforms.get_world_poses()
    env.robots.set_joint_position_targets(np.zeros((env.num_envs, 25))) # 
    print("thumb_pos", thumb_pos)