In [1]:
import numpy as np

In [2]:
from numpy_utils import *

In [4]:
grasp_rot = np.array([[0, 0.70711, 0, 0.70711]], dtype=np.float32).repeat(2, axis = 0) # XYZW

In [5]:
clock_wise = -1

In [20]:
theta = np.pi/4

In [21]:
rot_offset = np.array([[0, 0, np.sin( - clock_wise * theta / 2), np.cos( - clock_wise * theta / 2)]], dtype=np.float32).repeat(2, axis = 0)
  

In [22]:
rot_offset

array([[0.        , 0.        , 0.38268343, 0.9238795 ],
       [0.        , 0.        , 0.38268343, 0.9238795 ]], dtype=float32)

In [27]:
quat_mul(grasp_rot, rot_offset)

array([[0.27059925, 0.65328443, 0.27059925, 0.65328443],
       [0.27059925, 0.65328443, 0.27059925, 0.65328443]], dtype=float32)

In [26]:
 quat_mul(rot_offset, grasp_rot)

array([[-0.27059925,  0.65328443,  0.27059928,  0.65328443],
       [-0.27059925,  0.65328443,  0.27059928,  0.65328443]],
      dtype=float32)

# Rotation

In [2]:
from pxr import Gf
import numpy as np

In [4]:
a = np.array([[0.9304052 , 0.3656015 , 0.02435794, 0.00940057],
       [0.9304055 , 0.36560085, 0.0243575 , 0.00940162]], dtype=np.float32)

In [18]:
q = Gf.Quatf(float(a[0][3]), float(a[0][0]), float(a[0][1]), float(a[0][2]))

In [24]:
q = Gf.Quatf(0.70383,0.03774,0.70383,0.03774)

In [25]:
mat = Gf.Matrix4f().SetRotate(q)

In [28]:
mat.GetRow(2)[0]

0.9936019778251648