In [1]:
%load_ext autoreload
%autoreload 2

In [53]:
world.reset()

rties for. If you do not want the objects to collide, add colliders regardless then disable the 'enable collision' property.
2022-07-22 01:48:58 [113,300ms] [Warning] [omni.physx.plugin] The rigid body at /World/Game_01/mobility/base has a possibly invalid inertia tensor of {1.0, 1.0, 1.0} and a negative mass. Either specify correct values in the mass properties, or add collider(s) to any shape(s) that you wish to automatically compute mass properties for. If you do not want the objects to collide, add colliders regardless then disable the 'enable collision' property.
2022-07-22 01:54:39 [454,457ms] [Warning] [omni.physx.plugin] PhysicsUSD: Parse collision - triangle mesh collision (approximation None/MeshSimplifixation) cannot be a part of a dynamic body, falling back to convexHull approximation: /World/Game/mobility/link_0/visuals/handle_38
2022-07-22 01:54:39 [454,460ms] [Warning] [omni.physx.plugin] PhysicsUSD: Parse collision - triangle mesh collision (approximation None/MeshSimpl

In [3]:
import numpy as np

In [4]:
import getpass
user = getpass.getuser()

In [5]:
from omni.isaac.kit import SimulationApp

usd_path = f"omniverse://localhost/Users/{user}/test_franka2.usd"


simulation_app = SimulationApp({"headless": True, "open_usd": usd_path, "livesync_usd": usd_path})


Starting kit application with the fillowing args:  ['/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps', '--portable', '--no-window']
Passing the following args to the base kit application:  ['-f', '/home/yizhou/.local/share/jupyter/runtime/kernel-6053b1d7-6611-4cd0-a615-3ca9153a6112.json

OmniAssetFileFormat
2022-07-22 01:47:07 [2,015ms] [Error] [rtx.neuraylib.plugin] [DYNLIB:IO]   0.1   DYNLIB io   error: /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so: cannot open shared object file: No such file or directory
2022-07-22 01:47:07 [2,015ms] [Error] [rtx.neuraylib.plugin] [INDEX:MAIN]   0.1   INDEX  main error: Failed to load /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so


[1.694s] [ext: omni.mdl-0.1.0] startup
[1.715s] [ext: omni.kit.menu.create-1.0.2] startup
[1.716s] [ext: omni.kit.window.file_exporter-1.0.4] startup
[1.717s] [ext: omni.kit.window.drop_support-1.0.0] startup
[1.718s] [ext: omni.kit.material.library-1.3.10] startup
[1.720s] [ext: omni.kit.window.property-1.6.3] startup
[1.721s] [ext: omni.kit.context_menu-1.3.9] startup
[1.725s] [ext: omni.kit.window.file_importer-1.0.4] startup
[1.726s] [ext: omni.kit.stage_templates-1.1.2] startup
[1.727s] [ext: omni.kit.widget.stage-2.6.15] startup
[1.731s] [ext: omni.kit.window.file-1.3.16] startup
[1.733s] [ext: omni.debugdraw-0.1.0] startup
[1.739s] [ext: omni.kit.window.content_browser-2.4.28] startup
[1.750s] [ext: omni.kit.widget.prompt-1.0.1] startup
[1.751s] [ext: omni.kit.property.usd-3.14.8] startup
[1.786s] [ext: omni.hydra.engine.stats-1.0.0] startup
[1.792s] [ext: omni.kit.widget.settings-1.0.0] startup
[1.793s] [ext: omni.graph.tools-1.3.5] startup
[1.817s] [ext: omni.graph.core-2.27.0

2022-07-22 01:47:12 [7,278ms] [Warning] [omni.hydra] Mesh /World/Game/mobility/link_5/visuals/drawer_back_16 has corrupted data in primvar st: buffer size 24 doesn't match expected size 48 in faceVarying primvars
2022-07-22 01:47:12 [7,278ms] [Warning] [omni.hydra] Mesh /World/Game/mobility/link_5/visuals/drawer_bottom_17 has corrupted data in primvar st: buffer size 6 doesn't match expected size 12 in faceVarying primvars
2022-07-22 01:47:12 [7,278ms] [Warning] [omni.hydra] Mesh /World/Game/mobility/link_5/visuals/drawer_bottom_18 has corrupted data in primvar st: buffer size 6 doesn't match expected size 12 in faceVarying primvars
2022-07-22 01:47:12 [7,278ms] [Warning] [omni.hydra] Mesh /World/Game/mobility/link_5/visuals/handle_12 has corrupted data in primvar st: buffer size 1434 doesn't match expected size 3588 in faceVarying primvars
2022-07-22 01:47:12 [7,289ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_6/visuals/drawer_front_21 has corrupted data in primvar st: 

2022-07-22 01:47:12 [7,298ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_4/visuals/handle_23 has corrupted data in primvar st: buffer size 1434 doesn't match expected size 3588 in faceVarying primvars
2022-07-22 01:47:12 [7,298ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_4/visuals/drawer_bottom_29 has corrupted data in primvar st: buffer size 6 doesn't match expected size 12 in faceVarying primvars
2022-07-22 01:47:12 [7,298ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_front_13 has corrupted data in primvar st: buffer size 150 doesn't match expected size 300 in faceVarying primvars
2022-07-22 01:47:12 [7,298ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_front_14 has corrupted data in primvar st: buffer size 150 doesn't match expected size 300 in faceVarying primvars
2022-07-22 01:47:12 [7,298ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_front_15 has corrupted dat

2022-07-22 01:47:19 [14,192ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_front_20 has corrupted data in primvar st: buffer size 384 doesn't match expected size 768 in faceVarying primvars
2022-07-22 01:47:19 [14,192ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_front_21 has corrupted data in primvar st: buffer size 6 doesn't match expected size 12 in faceVarying primvars
2022-07-22 01:47:19 [14,192ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_front_22 has corrupted data in primvar st: buffer size 24 doesn't match expected size 48 in faceVarying primvars
2022-07-22 01:47:19 [14,192ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_front_23 has corrupted data in primvar st: buffer size 6 doesn't match expected size 12 in faceVarying primvars
2022-07-22 01:47:19 [14,192ms] [Warning] [omni.hydra] Mesh /World/Game_01/mobility/link_5/visuals/drawer_side_14 has corrupted d

In [6]:
from omni.isaac.core import World
world = World()

In [7]:
from open_env import OpenEnv

env = OpenEnv("/World/Game*/Franka", "/World/Game*/Franka/panda_hand")

In [8]:
world.reset()

: buffer size 1434 doesn't match expected size 3588 in faceVarying primvars
[15.091s] Simulation App Startup Complete
2022-07-22 01:47:21 [15,908ms] [Warning] [omni.physx.plugin] PhysicsUSD: Parse collision - triangle mesh collision (approximation None/MeshSimplifixation) cannot be a part of a dynamic body, falling back to convexHull approximation: /World/Game/mobility/link_0/visuals/handle_38
2022-07-22 01:47:21 [15,911ms] [Warning] [omni.physx.plugin] PhysicsUSD: Parse collision - triangle mesh collision (approximation None/MeshSimplifixation) cannot be a part of a dynamic body, falling back to convexHull approximation: /World/Game/mobility/link_1/visuals/handle_36
2022-07-22 01:47:21 [15,914ms] [Warning] [omni.physx.plugin] PhysicsUSD: Parse collision - triangle mesh collision (approximation None/MeshSimplifixation) cannot be a part of a dynamic body, falling back to convexHull approximation: /World/Game/mobility/link_2/visuals/handle_34
2022-07-22 01:47:21 [15,917ms] [Warning] [omn

In [9]:
env.start()

simlation context numpy None
num_envs 2


In [10]:
world.scene.add(env.robots)

In [56]:
# get grasp location
goal_pos, goal_rot = env.calculate_grasp_location(keyword = "handle_12", verticle = True)

In [57]:
env.robots.get_dof_limits()[0]

array([[-2.8973,  2.8973],
       [-1.7628,  1.7628],
       [-2.8973,  2.8973],
       [-3.0718, -0.0698],
       [-2.8973,  2.8973],
       [-0.0175,  3.7525],
       [-2.8973,  2.8973],
       [ 0.    ,  0.04  ],
       [ 0.    ,  0.04  ]], dtype=float32)

# first stage: move the correct y,z, keep x far 

In [58]:
goal_pos[...,0] -= 0.15

In [59]:
goal_pos, goal_rot

(array([[0.37157962, 0.4178389 , 0.6150211 ],
        [0.37157962, 2.4178388 , 0.6150211 ]], dtype=float32),
 array([[0.5, 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, 0.5]], dtype=float32))

In [60]:
# bboxes_list = env.get_mesh_bboxes("handle_")
# center_list = [(e[1] + e[0]) / 2 for e in bboxes_list]

# center_list[0][0] -= 0.2
# center_list[1][0] -= 0.2

# goal_pos = np.array([list(e) for e in center_list], dtype=np.float32)
# goal_rot = np.array([[0, 0.70711, 0, 0.70711]], dtype=np.float32).repeat(2, axis = 0) # XYZW

# # goal_pos, goal_rot = hand_pos, hand_rot

In [61]:
from usd_utils import calcuate_rotation_axis
from numpy_utils import quat_conjugate, quat_mul

In [62]:
goal_rot

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]], dtype=float32)

In [63]:
env.move_hand_to_fast(goal_pos, goal_rot, world, max_step=300)

Done rotation, position [[0.37176386 0.4176955  0.61464566]
 [0.37176365 2.4176955  0.614646  ]] [[0.5120684  0.4887937  0.50708526 0.4916617 ]
 [0.51206833 0.48879364 0.5070857  0.4916614 ]]


In [64]:
# # stage
# for _ in range(300):
#     world.step(render=True)
    
#     # get end effector transforms
#     hand_pos, hand_rot = env.xforms.get_world_poses()
#     hand_rot = hand_rot[:,[1,2,3,0]] # WXYZ -> XYZW
    
#     if abs(quat_mul(goal_rot[0], quat_conjugate(hand_rot[0]))[3] - 1) < 0.03 and \
#         np.sqrt(np.sum((goal_pos[0] - hand_pos[0])**2)) < 0.01:
#         print(hand_rot)
#         print("Done rotation, position")
#         break

#     u = env.move_to_target(goal_pos, goal_rot)
#     u[:,[-2, -1]] = 0.05
#     env.robots.set_joint_position_targets(u)

# Second Stage: move to the grasp position

In [65]:
goal_pos[...,0] += 0.15

# center_list[0][0] -= 0.1
# center_list[1][0] -= 0.1
# goal_pos = np.array([list(e) for e in center_list], dtype=np.float32)
# goal_rot = np.array([[0, 0.70711, 0, 0.70711]], dtype=np.float32).repeat(2, axis = 0) # XYZW

In [66]:
goal_pos

array([[0.5215796, 0.4178389, 0.6150211],
       [0.5215796, 2.4178388, 0.6150211]], dtype=float32)

In [67]:
env.move_hand_to_slow(goal_pos, goal_rot, world, step = 60)

In [68]:
# for i in range(60):
#     world.step(render=True)
    
#     u = env.move_to_target(goal_pos, goal_rot)
#     u[:,[-2, -1]] = 0.5 
#     env.robots.set_joint_position_targets(u)

# Third Stage: close gripper

In [69]:
# env.move_hand_to_slow(goal_pos, goal_rot, world, open_gripper=False, step = 60)

In [70]:
for i in range(60):
    world.step(render=True)
    
    u = env.move_to_target(goal_pos, goal_rot)
    u[:,[-2, -1]] = 0.5 - (0.5 - -1) / 60 * i
    env.robots.set_joint_position_targets(u)

# Forth Stage: Pull Open

1. Open from the right

In [26]:
# rotate and pull
for i in range(60):
    world.step(render=True)
    
    target_pos, target_rot = env.calculate_pull_location(goal_pos, goal_rot, np.pi / 180 * i, 0.3)
    u = env.move_to_target(target_pos, target_rot)
    u[:,[-2, -1]] = -1
    env.robots.set_joint_position_targets(u)

2. Open from the left

In [52]:
# rotate and pull
for i in range(10, 60):
    world.step(render=True)
    
    target_pos, target_rot = env.calculate_pull_location(goal_pos, goal_rot, np.pi / 180 * i, 0.3, clock_wise=True)
    u = env.move_to_target(target_pos, target_rot)
    u[:,[-2, -1]] = -1
    env.robots.set_joint_position_targets(u)

3. Pull the drawer out

In [71]:
# pull only
for i in range(60):
    world.step(render=True)
    
    goal_pos[...,0] -= 2e-4 * i
    u = env.move_to_target(goal_pos, goal_rot)
    u[:,[-2, -1]] = -1
    env.robots.set_joint_position_targets(u)

In [ ]:
## cannot slerp
# end_pos, end_rot = env.calculate_pull_location(goal_pos, goal_rot, np.pi / 3, 0.3)
# env.move_hand_to_slow(end_pos, end_rot, world, open_gripper=False, step = 60)

In [ ]:
world.reset()
world.render()

In [ ]:
pause