In [1]:
import numpy as np

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
# world.reset()

In [4]:
import getpass
user = getpass.getuser()

In [5]:
from omni.isaac.kit import SimulationApp

usd_path = f"omniverse://localhost/Users/{user}/test_hand2.usd"


simulation_app = SimulationApp({"headless": True, "open_usd": usd_path, "livesync_usd": usd_path})


Starting kit application with the fillowing args:  ['/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps', '--portable', '--no-window']
Passing the following args to the base kit application:  ['-f', '/home/yizhou/.local/share/jupyter/runtime/kernel-b8b587c2-4a95-4cc2-b71b-a8d18c16cbca.json

OmniAssetFileFormat
2022-07-26 17:41:24 [1,908ms] [Error] [rtx.neuraylib.plugin] [DYNLIB:IO]   0.1   DYNLIB io   error: /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so: cannot open shared object file: No such file or directory
2022-07-26 17:41:24 [1,908ms] [Error] [rtx.neuraylib.plugin] [INDEX:MAIN]   0.1   INDEX  main error: Failed to load /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so


[1.556s] [ext: omni.mdl-0.1.0] startup
[1.577s] [ext: omni.kit.menu.create-1.0.2] startup
[1.579s] [ext: omni.kit.window.file_exporter-1.0.4] startup
[1.580s] [ext: omni.kit.window.drop_support-1.0.0] startup
[1.581s] [ext: omni.kit.material.library-1.3.10] startup
[1.584s] [ext: omni.kit.window.property-1.6.3] startup
[1.586s] [ext: omni.kit.context_menu-1.3.9] startup
[1.590s] [ext: omni.kit.window.file_importer-1.0.4] startup
[1.591s] [ext: omni.kit.stage_templates-1.1.2] startup
[1.594s] [ext: omni.kit.widget.stage-2.6.15] startup
[1.599s] [ext: omni.kit.window.file-1.3.16] startup
[1.602s] [ext: omni.debugdraw-0.1.0] startup
[1.608s] [ext: omni.kit.window.content_browser-2.4.28] startup
[1.620s] [ext: omni.kit.widget.prompt-1.0.1] startup
[1.621s] [ext: omni.kit.property.usd-3.14.8] startup
[1.666s] [ext: omni.hydra.engine.stats-1.0.0] startup
[1.673s] [ext: omni.kit.widget.settings-1.0.0] startup
[1.675s] [ext: omni.graph.tools-1.3.5] startup
[1.708s] [ext: omni.graph.core-2.27.0

In [6]:
from omni.isaac.core import World
world = World()

In [7]:
from hand_env import HandEnv

# env = HandEnv("/World/Hand/Bones/l_carpal_mid", "/World/Hand*/Bones/l_thumbSkeleton_grp/l_distalThumb_mid")
env = HandEnv("/World/Hand*", "/World/Hand*/Bones/l_thumbSkeleton_grp/l_distalThumb_mid")

In [8]:
world.reset()

p
[5.639s] [ext: omni.isaac.surface_gripper-0.1.2] startup
[5.644s] [ext: omni.kit.property.layer-1.1.2] startup
[5.646s] [ext: omni.isaac.range_sensor-0.4.2] startup
[5.674s] [ext: omni.graph.window.generic-1.3.8] startup
[5.675s] [ext: omni.isaac.utils-0.1.11] startup
[5.679s] [ext: omni.isaac.universal_robots-0.2.1] startup
[5.680s] [ext: omni.kit.property.audio-1.0.5] startup
[5.681s] [ext: omni.kit.property.skel-1.0.1] startup
[5.683s] [ext: omni.kit.property.render-1.1.0] startup
[5.684s] [ext: omni.kit.property.camera-1.0.3] startup
[5.685s] [ext: omni.kit.property.geometry-1.2.0] startup
[5.687s] [ext: omni.kit.property.light-1.0.5] startup
[5.688s] [ext: omni.kit.property.transform-1.0.2] startup
[5.691s] [ext: omni.isaac.occupancy_map-0.2.4] startup
[5.705s] [ext: omni.ui.scene-1.4.6] startup
[5.711s] [ext: omni.kit.window.console-0.2.0] startup
[5.718s] [ext: omni.kit.window.status_bar-0.1.1] startup
[5.722s] [ext: omni.kit.property.bundle-1.2.4] startup
[5.724s] [ext: omni.

In [9]:
env.start()
world.scene.add(env.robots)

simlation context numpy None
num_envs 1


In [70]:
hand_pos, hand_rot = env.robots.get_world_poses()

In [72]:
hand_pos[...,0] += 10

In [73]:
hand_pos

array([[ 1.1000001e+01, -9.5367432e-07,  7.1525574e-07]], dtype=float32)

In [74]:
env.robots.set_world_poses(hand_pos, hand_rot)

In [65]:
# pos = np.array([[ 0.5, -0., 0.5]], dtype=np.float32)
# env.robots.set_world_poses(positions=pos)

In [78]:
world.reset()

In [80]:
world.step(render=True)

In [81]:
env.robots.get_joint_positions()

array([[ 9.4866209e-06, -1.6463640e-05,  2.3469307e-05, -2.3274793e-06,
         2.5486603e-05, -1.5733254e-06,  2.1189167e-05,  1.1389776e-05,
         2.5035077e-05,  7.2182451e-07, -5.4054559e-05, -1.2985406e-05,
        -6.3140046e-06,  3.1785476e-05,  2.0590605e-07, -1.0324828e-06,
        -1.9084757e-07, -9.5530041e-08,  2.9557515e-07, -1.8841829e-11]],
      dtype=float32)

In [87]:
env.robots._physics_view.dof_paths

[['/World/Hand/Bones/l_thumbSkeleton_grp/l_metacarpalThumb_mid/Thumb_metacarpal_D6DriverJoint',
  '/World/Hand/Bones/l_thumbSkeleton_grp/l_metacarpalThumb_mid/Thumb_metacarpal_D6DriverJoint',
  '/World/Hand/Bones/l_indexSkeleton_grp/l_proximalIndex_mid/Index_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_indexSkeleton_grp/l_proximalIndex_mid/Index_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_middleSkeleton_grp/l_proximalMiddle_mid/Middle_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_middleSkeleton_grp/l_proximalMiddle_mid/Middle_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_pinkySkeleton_grp/l_proximalPinky_mid/Pinky_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_pinkySkeleton_grp/l_proximalPinky_mid/Pinky_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_ringSkeleton_grp/l_proximalRing_mid/Ring_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_ringSkeleton_grp/l_proximalRing_mid/Ring_proximal_D6DriverJoint',
  '/World/Hand/Bones/l_thumbSkeleton_grp/l_proximalThumb_mid/Thumb_proxi

In [16]:
pause

NameError: name 'pause' is not defined

In [90]:
import time

In [107]:
for i in range(20):
    pos = np.array([
        [ 0,  0, 
          i * 0.01,  0,  
          0, 0, 
         -i * 0.02, 0,  
         -i * 0.01, 0,  
         -i * 0.03,  -i * 0.03,  -i * 0.03,  -i * 0.03,  -i * 0.05,
          -i * 0.03,  -i * 0.03,  -i * 0.03,  -i * 0.03,  -i * 0.05, 
        ],
    ])

    # pos = np.random.randn(2,25)
    time.sleep(0.2)
    env.robots.set_joint_positions(pos) # 
    world.step(render=True)

In [89]:
env.robots.get_joint_positions()

array([[ 1.1039621e-05, -1.7362234e-05,  2.3441187e-05, -2.4588705e-06,
         2.4485584e-05, -1.5477821e-06,  2.1189167e-05,  1.1389776e-05,
         2.4589272e-05,  1.0380746e-06, -5.6652239e-05, -1.2629806e-05,
        -5.8826831e-06,  3.1803011e-05,  5.6256494e-07, -1.0819101e-06,
        -1.8555318e-07, -8.8853412e-08,  2.9574633e-07,  5.1813820e-09]],
      dtype=float32)

In [ ]:
joint_v = np.array([[
     1,  0,  
     0., 0.,
     0., 0., 
     0., 0., 
     0., 0., 
     0, 0, 0, 0, 0,
     0, 0, 0, 0, 0
]]).transpose()

In [ ]:
joint_v.shape

In [ ]:
jacobians = env.robots._physics_view.get_jacobians()

In [ ]:
jacobians.shape

In [ ]:
delta_pos_rot = np.matmul(jacobians[0], joint_v)
for i in range(len(delta_pos_rot)):
    print(i, delta_pos_rot[i].transpose())

# Jacobian

In [17]:
world.reset()
world.step(render=True)

In [18]:
thumb_pos, thumb_rot = env.xforms.get_world_poses()

In [19]:
thumb_rot = thumb_rot[:,[1,2,3,0]] # WXYZ -> XYZW

In [20]:
thumb_pos, thumb_rot

(array([[-3.120222 , -1.1239259,  2.802331 ]], dtype=float32),
 array([[-0.15511908, -0.16415861, -0.23857737,  0.944495  ]],
       dtype=float32))

In [21]:
target_pos = thumb_pos.copy()#np.array([[-0.37809137,  -0.3650283  , 0.05804292]])

In [44]:
target_pos[...,1] -= 0.5

In [48]:
target_pos

array([[-3.120222 , -1.1239259,  2.802331 ]])

In [50]:
env.move_finger_to_fast(target_pos, thumb_rot, world, finger = "thumb")

finger_pos [[-2.8123133 -0.7832121  3.0709372]]
finger_pos [[-2.8148513 -0.786094   3.0695825]]
finger_pos [[-2.8173532 -0.788942   3.068221 ]]
finger_pos [[-2.8198357 -0.7917575  3.0668638]]
finger_pos [[-2.8222854  -0.79454076  3.0655103 ]]
finger_pos [[-2.8247192 -0.7972913  3.0641656]]
finger_pos [[-2.8271196  -0.80001235  3.0628183 ]]
finger_pos [[-2.8294964 -0.8027027  3.0614698]]
finger_pos [[-2.8318439  -0.80536157  3.0601273 ]]
finger_pos [[-2.8341737  -0.80799246  3.0587866 ]]
finger_pos [[-2.836484   -0.81059486  3.0574527 ]]
finger_pos [[-2.8387663 -0.8131686  3.056119 ]]
finger_pos [[-2.8410206 -0.8157097  3.054789 ]]
finger_pos [[-2.8432565 -0.8182303  3.0534601]]
finger_pos [[-2.8454633  -0.82071954  3.05213   ]]
finger_pos [[-2.8476524 -0.8231852  3.0508063]]
finger_pos [[-2.8498228  -0.82562536  3.0494866 ]]
finger_pos [[-2.851977   -0.82804275  3.0481741 ]]
finger_pos [[-2.8541076  -0.83043104  3.04686   ]]
finger_pos [[-2.8562143  -0.83279806  3.0455449 ]]
finger_pos

In [ ]:
target_pos = np.zeros((env.num_envs, 20)) 
# target_pos = np.random.randn(env.num_envs, 20) 

In [ ]:
env.num_envs

In [ ]:
target_pos

In [ ]:
for _ in range(100):
    world.step(render=True)
    thumb_pos, thumb_rot = env.xforms.get_world_poses()
    env.robots.set_joint_position_targets(target_pos) 
    print("thumb_pos", thumb_pos)

In [ ]:
env.robots.get_joint_positions()